function(vox_detect_platform out_var)
    if(WIN32)
        set(${out_var} "Windows" PARENT_SCOPE)
    elseif(APPLE)
        set(${out_var} "macOS" PARENT_SCOPE)
    elseif(UNIX)
        set(${out_var} "Linux" PARENT_SCOPE)
    else()
        set(${out_var} "Unknown" PARENT_SCOPE)
    endif()
endfunction()
